### ISSUE TITLE
Import Action Bar Icon Pack

### ISSUE THREAD

**Issue by keith-pinto** [vivek716/My_First_App#5]
1. Download the icon pack from [here](https://developer.android.com/downloads/design/Android_Design_Icons_20131106.zip)
2. Check this [SO link](http://stackoverflow.com/questions/12709255/how-to-import-add-icons-from-the-icon-pack-template-pack-into-my-android-app) on how to import graphics into a project
3. Mark this issue as done, once its done. Yo!

**Comment by vivek716** [comment]
Done!

**Comment by vivek716** [comment]
Problem?
